# docker-compose.yml
version: "3.1"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./db/data:/var/lib/postgresql/data
  backend:
    build: "./backend"
    ports:
      - "3001:3001"
    depends_on:
      - "db"
    volumes:
      - ./backend:/app
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
    volumes:
      - ./frontend:/app
